### PR TITLE
[SEDONA-520] Add apache-commons jar to snowflake dependencies

### PR DESCRIPTION
**Pull request by Kontinuation**
## Did you read the Contributor Guide?

- Yes, I have read [Contributor Rules](https://sedona.apache.org/latest-snapshot/community/rule/) and [Contributor Development Guide](https://sedona.apache.org/latest-snapshot/community/develop/)

## Is this PR related to a JIRA ticket?

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-520. The PR name follows the format `[SEDONA-XXX] my subject`.

## What changes were proposed in this PR?

Added missing commons-lang3 dependency to snowflake/pom.xml.

## How was this patch tested?

Passed the snowflake CI.

## Did this PR include necessary documentation updates?

- No, this PR does not affect any public API so no need to change the docs.

### CODE REVIEW

**Comment by Kontinuation** [comment]
There is a separated PR for updating the snowflake CI https://github.com/wherobots/sedona-snowflake-tester/pull/21/files. This needs to be merged.

**Comment by Kontinuation** [comment]
@jiayuasu Is there any repository-level settings for `SNOWFLAKE_GEOTOOLS_VERSION` environment variable? I've changed the environment variable in snowflake-tester.yml but the workflow job is still using the old version.

**Comment by jiayuasu** [comment]
@Kontinuation No, this repo does not have any repo level setting for geotools version. See 
image


The organization also has no org level variables at all

**Comment by jiayuasu** [comment]
BTW, 2 concurrent Snowflake PR will conflict with each other since they both use the same database and stages

**Comment by jiayuasu** [comment]
I have confirmed that now the snowflake tester is picking up 1.5.1-28.2

**Comment by Kontinuation** [comment]
I've re-run the CI and it has passed: https://github.com/wherobots/sedona-snowflake-tester/actions/runs/8410338354/job/23028649572?pr=20. The fix seems to be valid.

**Pull request closed without merging**
